**IDS Assignment 04**
* Ahmad Faisal
* BSDSF21A034

- Task 1

In [ ]:
import numpy as np

# Generate random temperature data for 500 locations over 365 days
# Temperature values range from -10 to 40 degrees Celsius
temperature_data = np.random.uniform(-10, 40, (500, 365))

# Generate random humidity data for 500 locations over 365 days
# Humidity percentages range from 0% to 100%
humidity_data = np.random.uniform(0, 100, (500, 365))

print("Temperature and humidity data initialized.")
temperature_data


Temperature and humidity data initialized.


array([[29.44115923, 18.86892575, -7.67466811, ..., -9.49519473,
        -5.66563788, 14.85322829],
       [39.58431286, 28.00487175,  7.93356106, ..., 30.31145061,
         0.47073733, 21.64885155],
       [12.0807892 , -2.60435518, 24.11483442, ..., 27.76974816,
         8.89975803, 21.36570787],
       ...,
       [22.59583355, 36.27246963, 35.37566236, ..., -0.47893403,
        -2.91457617,  3.12551862],
       [11.66084408, -2.91752808, 11.67146611, ..., 30.05220045,
        25.71421168,  0.30870231],
       [-3.19878061, -4.46226471, 14.40103209, ..., 35.40500681,
        30.30058457, -2.91798004]])

- Task 2

In [32]:
# Set 5% of values in temperature_data and humidity_data to None (simulate missing data)
missing_indices_temp = np.random.choice(temperature_data.size, int(0.05 * temperature_data.size), replace=False)
missing_indices_humid = np.random.choice(humidity_data.size, int(0.05 * humidity_data.size), replace=False)

# Convert indices to row, column format and set values to NaN for missing data simulation
temperature_data.flat[missing_indices_temp] = np.nan
humidity_data.flat[missing_indices_humid] = np.nan

# Calculate the number of missing values in each dataset
temp_missing_count = np.isnan(temperature_data).sum()
humid_missing_count = np.isnan(humidity_data).sum()

print(f"Total missing values in temperature data: {temp_missing_count}")
print(f"Total missing values in humidity data: {humid_missing_count}")


Total missing values in temperature data: 9125
Total missing values in humidity data: 9125


- Task 3

In [35]:
# Convert Celsius temperatures to Fahrenheit
temperature_fahrenheit = (temperature_data * 9/5) + 32

# Calculate "feels like" discomfort index: a simple weighted sum of temperature and humidity
# Here, we'll use 0.7 * temperature + 0.3 * humidity as a sample formula for "feels like"
# Use `np.nan_to_num` to handle NaNs in discomfort index
discomfort_index = np.nan_to_num(0.7 * temperature_fahrenheit + 0.3 * humidity_data)

# Cap the discomfort index values at 80
discomfort_index = np.clip(discomfort_index, None, 80)

print("Temperature converted to Fahrenheit and discomfort index calculated.")
print(temperature_fahrenheit)
discomfort_index

Temperature converted to Fahrenheit and discomfort index calculated.
[[ 84.99408662  65.96406636  18.1855974  ...  14.90864948  21.80185181
   58.73581093]
 [103.25176315  82.40876915  46.28040991 ...  86.5606111   32.8473272
   70.9679328 ]
 [ 53.74542055  27.31216068  75.40670196 ...  81.98554668  48.01956445
   70.45827416]
 ...
 [ 72.67250038  97.29044534  95.67619225 ...  31.13791875  26.75376289
   37.62593351]
 [ 52.98951934  26.74844945  53.00863899 ...  86.0939608   78.28558102
   32.55566417]
 [ 26.2421949   23.96792351  57.92185776 ...  95.72901225  86.54105223
   26.74763593]]


array([[60.76327999, 63.29812738, 33.12970194, ..., 26.20656366,
        23.38313985, 55.37534618],
       [80.        , 60.97606706, 49.18315541, ..., 72.35835859,
        35.48917933, 54.88916373],
       [54.55702265, 29.69979817, 69.73127819, ..., 80.        ,
        52.44470509, 59.54083336],
       ...,
       [73.03998311, 80.        , 80.        , ..., 44.78923342,
        42.89974055, 48.96258953],
       [59.34525061, 44.53552154, 53.56834184, ..., 61.25308654,
        59.09316018, 43.15924054],
       [21.71623487, 17.90471713,  0.        , ..., 80.        ,
        74.17597634, 26.8269056 ]])

- Task 4

In [42]:
# Extract temperatures for the first 31 days (January)
january_temperatures = temperature_data[:, :31]

# Calculate the average January temperature across all 500 locations
january_avg_temp = np.nanmean(january_temperatures)

print(f"Average January temperature across all locations: {january_avg_temp:.2f} °C")


Average January temperature across all locations: 15.00 °C


- Task 5

In [43]:
# Mark temperatures over 35°C as potential errors by setting them to NaN
temperature_data[temperature_data > 35] = np.nan

# Count the number of NaN values per location
null_count_per_location = np.isnan(temperature_data).sum(axis=1)

print("Extreme temperatures marked as NaN.")
print("Number of NaNs per location:", null_count_per_location)


Extreme temperatures marked as NaN.
Number of NaNs per location: [51 58 46 43 62 55 65 47 58 67 55 48 54 48 49 49 54 47 63 59 49 47 54 62
 62 45 62 45 67 42 53 49 60 44 47 60 53 53 61 43 49 50 61 59 56 62 53 54
 60 61 51 50 44 55 52 64 52 52 59 51 53 55 56 41 53 44 56 53 43 53 51 45
 54 51 49 57 49 58 52 53 53 50 44 66 52 54 53 54 44 53 58 41 54 52 64 64
 55 49 53 44 54 47 51 51 49 49 59 54 66 51 57 54 53 57 48 57 52 47 51 51
 58 59 56 60 61 47 52 52 54 57 46 53 49 46 51 52 49 42 61 58 42 59 49 56
 51 57 47 48 60 65 58 61 52 55 51 54 56 52 43 58 59 51 62 49 57 56 51 61
 48 62 49 59 64 48 41 47 49 49 53 47 58 46 52 67 50 63 53 60 51 53 54 47
 44 53 50 51 47 43 51 53 62 52 59 59 45 60 58 49 53 59 52 53 54 52 55 47
 57 48 59 53 59 43 50 52 48 53 59 53 60 51 55 58 57 64 54 63 54 51 43 62
 56 53 53 54 44 57 43 61 46 54 66 53 49 57 58 53 47 51 47 45 47 43 60 64
 48 45 49 55 52 48 64 61 47 58 47 60 52 55 56 55 56 46 54 42 49 67 51 56
 67 63 44 49 59 54 47 58 66 49 53 48 52 53 62 55 60 41 48 4

- Task 6

In [55]:
# Reshape temperature data into four quarters (each with approximately 91 days)
# temperature_data_quarters = temperature_data.reshape(500, 4, -1)
# This was giving error: ValueError: cannot reshape array of size 182500 into shape (500,4,newaxis)
# so we will Pad the data to reach (500 * 4 * 92)
temperature_data_padded = temperature_data.flatten()
temperature_data_padded = np.pad(temperature_data_padded, (0, 1500), mode='constant', constant_values=np.nan)
temperature_data_quarters = temperature_data_padded.reshape(500, 4, 92)


# Calculate the average temperature for each location for each quarter
quarterly_avg_temperatures = np.nanmean(temperature_data_quarters, axis=2)

# Remove rows where all quarterly averages are NaN
quarterly_avg_temperatures = quarterly_avg_temperatures[~np.isnan(quarterly_avg_temperatures).all(axis=1)]

print("Quarterly average temperatures calculated for each location:")
print(quarterly_avg_temperatures)


Quarterly average temperatures calculated for each location:
[[12.15564778 11.80901729 12.57416647 11.85959284]
 [12.89714704 10.22366735 12.3830414  12.79432451]
 [12.53607105 11.77213233 13.69492948 13.19283561]
 ...
 [13.6742443   9.434188   14.38074332  9.37949313]
 [12.73383943 12.26343359 13.31853003 11.49234078]
 [11.09106596 15.92111769 13.17327875 13.58361841]]


C:\Users\jstah\AppData\Local\Temp\ipykernel_6760\549732352.py:11: RuntimeWarning: Mean of empty slice
  quarterly_avg_temperatures = np.nanmean(temperature_data_quarters, axis=2)


- Task 7

In [57]:
# Classify each day's humidity level as "Dry" (humidity < 30%) or "Humid" (humidity > 70%)
dry_days = humidity_data < 30
humid_days = humidity_data > 70

# Count total "Dry" and "Humid" days for each location
dry_day_count = np.sum(dry_days, axis=1)
humid_day_count = np.sum(humid_days, axis=1)

print("Dry and Humid day counts for each location:")
print("Dry days:", dry_day_count)

print("\nHumid days:", humid_day_count)


Dry and Humid day counts for each location:
Dry days: [105 113 118 123 114 107  99  92 107 105 104 102 107  93 113 103 103  83
 112 116 107 100 107 101 100  98 112  95 106  94 111 108 108  99 123 119
 128 104 112 105  92 102 108  97 111 103  89 121 101 112 101 109 104 103
 101 112  87 113  99  90 111 102  98  93 107 104 109  95  96 108  88  92
 109 107 105 105 105 108 115  99 102 110 105 102  89 106 102 111 103  98
 119 108 107 100  95 113 108 106 106  98 104  91 104 102 102 106 101  90
 108  95 105 101 106  89 109 110 115 104 113 103 113 105 113 126 118  89
  86 112  92  96 109 111 105 107 114  93 111 101  91 102 100 114 101 110
 105 106 118  95 108 105 112 101 107 122 114  97  93  97 102  97 104 102
  99  96  96 110 106 104  89  90  96 114 119 104 106  87  91 104  91 101
 109  96  89 117  98 105 106 110  92 105  99  98 101  93 117  98 100  96
 113 102 114 113  87 103 109 115 102  97  93  86 100  97 104 104  99 109
 114 101 115 100 113 101 104 108 107 105 116 102 112 103 107  97  95 1

- Task 8

In [58]:
# Generate a daily pressure trend across 365 days (e.g., a sinusoidal trend for seasonal effect)
# We'll create a simple sine wave to represent the pressure change
pressure_trend = 5 * np.sin(np.linspace(0, 2 * np.pi, 365))

# Apply the pressure trend to adjust temperatures at each location (add to each row)
temperature_adjusted = temperature_data + pressure_trend

print("Daily pressure trend applied to temperature data.")
temperature_adjusted

Daily pressure trend applied to temperature data.


array([[29.44115923, 18.95522896, -7.50208742, ..., -9.66777543,
        -5.75194109, 14.85322829],
       [        nan, 28.09117496,  8.10614176, ..., 30.13886991,
         0.38443413, 21.64885155],
       [12.0807892 , -2.51805197, 24.28741512, ..., 27.59716746,
         8.81345483, 21.36570787],
       ...,
       [22.59583355,         nan,         nan, ..., -0.65151472,
        -3.00087938,  3.12551862],
       [11.66084408, -2.83122488, 11.8440468 , ..., 29.87961975,
        25.62790847,  0.30870231],
       [-3.19878061, -4.37596151, 14.57361278, ...,         nan,
        30.21428137, -2.91798004]])