# Lab 02

**Ahmad Faisal**

**BSDSF21A034**

### Task 01 ###

* Import Libraries

In [1]:
import numpy as np

* Create a NumPy array for player statistics

In [2]:
# Format: [Height (cm), Weight (kg), Points Scored]
player_stats = np.array([
    [180, 75, 20],
    [175, 68, 15],
    [190, 85, 30],
    [165, 60, 10]
])
print("Initial Player Statistics:\n", player_stats)


Initial Player Statistics:
 [[180  75  20]
 [175  68  15]
 [190  85  30]
 [165  60  10]]


* Update the weight of the player with the maximum points scored

In [3]:
# Find the index of the player with the maximum points scored
max_points_index = np.argmax(player_stats[:, 2])

# Update their weight (e.g., add 5 kg)
player_stats[max_points_index, 1] += 5
print("\nUpdated Player Statistics (Weight of Max Scorer Updated):\n", player_stats)


Updated Player Statistics (Weight of Max Scorer Updated):
 [[180  75  20]
 [175  68  15]
 [190  90  30]
 [165  60  10]]


*  Append a new player's statistics to the array

In [4]:
# New player stats: [Height, Weight, Points Scored]
new_player = [185, 80, 25]
player_stats = np.vstack([player_stats, new_player])
print("\nPlayer Statistics After Adding a New Player:\n", player_stats)


Player Statistics After Adding a New Player:
 [[180  75  20]
 [175  68  15]
 [190  90  30]
 [165  60  10]
 [185  80  25]]


* Insert a new statistic at a specified index within the array

In [5]:
# Insert a new player at index 2
new_statistic = [170, 65, 18]
player_stats = np.insert(player_stats, 2, new_statistic, axis=0)
print("\nPlayer Statistics After Inserting a New Statistic:\n", player_stats)



Player Statistics After Inserting a New Statistic:
 [[180  75  20]
 [175  68  15]
 [170  65  18]
 [190  90  30]
 [165  60  10]
 [185  80  25]]


* Delete the player with the lowest points scored

In [6]:
# Find the index of the player with the lowest points scored
min_points_index = np.argmin(player_stats[:, 2])

# Delete the player
player_stats = np.delete(player_stats, min_points_index, axis=0)
print("\nPlayer Statistics After Deleting the Player with Lowest Points:\n", player_stats)



Player Statistics After Deleting the Player with Lowest Points:
 [[180  75  20]
 [175  68  15]
 [170  65  18]
 [190  90  30]
 [185  80  25]]


### Task 02 ###

* Create two NumPy arrays for purchase amounts and item counts

In [7]:
# Purchase amounts in dollars
purchase_amounts = np.array([150, 200, 50, 300, 120])

# Item counts for each purchase
item_counts = np.array([3, 4, 1, 5, 2])

print("Purchase Amounts:", purchase_amounts)
print("Item Counts:", item_counts)


Purchase Amounts: [150 200  50 300 120]
Item Counts: [3 4 1 5 2]


* Create a shallow copy of one and a deep copy of the other

In [8]:
# Shallow copy of purchase amounts
purchase_shallow_copy = purchase_amounts.view()

# Deep copy of item counts
item_deep_copy = item_counts.copy()

print("\nShallow Copy of Purchase Amounts:", purchase_shallow_copy)
print("Deep Copy of Item Counts:", item_deep_copy)



Shallow Copy of Purchase Amounts: [150 200  50 300 120]
Deep Copy of Item Counts: [3 4 1 5 2]


* Concatenate both arrays

In [9]:
# Concatenate purchase amounts and item counts
combined_array = np.concatenate((purchase_amounts, item_counts))
print("\nConcatenated Array:", combined_array)



Concatenated Array: [150 200  50 300 120   3   4   1   5   2]


* Split the concatenated array based on a condition

In [10]:
# Split into two arrays: values greater than 100 and others
greater_than_100 = combined_array[combined_array > 100]
less_or_equal_100 = combined_array[combined_array <= 100]

print("\nValues Greater Than 100:", greater_than_100)
print("Values Less or Equal to 100:", less_or_equal_100)



Values Greater Than 100: [150 200 300 120]
Values Less or Equal to 100: [50  3  4  1  5  2]


*  Modify the original arrays and analyze the effects on the copies

In [11]:
# Modify the original arrays
purchase_amounts[0] = 180  # Change the first purchase amount
item_counts[1] = 6         # Change the second item count

print("\nModified Purchase Amounts:", purchase_amounts)
print("Modified Item Counts:", item_counts)

# Effects on the copies
print("\nShallow Copy After Modification:", purchase_shallow_copy)
print("Deep Copy After Modification (Unchanged):", item_deep_copy)



Modified Purchase Amounts: [180 200  50 300 120]
Modified Item Counts: [3 6 1 5 2]

Shallow Copy After Modification: [180 200  50 300 120]
Deep Copy After Modification (Unchanged): [3 4 1 5 2]
