***IDS Lab 01***

Ahmad Faisal

BSDSF21A034
______________________________________________________________________________________________________________________________________

- Task 1

In [10]:
import numpy as np

arr = np.arange(1, 21)
print ("1D array of integers from 1 to 20: ", arr)


arr_2d = arr.reshape(4, 5)
print ("4x5 2D array: \n",arr_2d)


arr_2d[:, -1] = 0
print ("After replacement last column with zeros: \n",arr_2d)


arr_flattened = arr_2d.flatten()
print("Final flattened array:", arr_flattened)


1D array of integers from 1 to 20:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
4x5 2D array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
After replacement last column with zeros: 
 [[ 1  2  3  4  0]
 [ 6  7  8  9  0]
 [11 12 13 14  0]
 [16 17 18 19  0]]
Final flattened array: [ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]



- Task 2

In [11]:
arr_2d_random = np.random.randint(10, 51, (5, 5))


print("Array:\n", arr_2d_random)
print("\nRow-wise calculations:")
for i, row in enumerate(arr_2d_random):
    print(f"Row {i+1} - Mean: {row.mean()}, Sum: {row.sum()}, Min: {row.min()}, Max: {row.max()}")


print("\nColumn-wise calculations:")
for j in range(arr_2d_random.shape[1]):
    col = arr_2d_random[:, j]
    print(f"Column {j+1} - Mean: {col.mean()}, Sum: {col.sum()}, Min: {col.min()}, Max: {col.max()}")


Array:
 [[21 17 15 25 12]
 [27 43 20 33 28]
 [46 17 39 44 22]
 [35 43 22 21 40]
 [23 44 38 39 40]]

Row-wise calculations:
Row 1 - Mean: 18.0, Sum: 90, Min: 12, Max: 25
Row 2 - Mean: 30.2, Sum: 151, Min: 20, Max: 43
Row 3 - Mean: 33.6, Sum: 168, Min: 17, Max: 46
Row 4 - Mean: 32.2, Sum: 161, Min: 21, Max: 43
Row 5 - Mean: 36.8, Sum: 184, Min: 23, Max: 44

Column-wise calculations:
Column 1 - Mean: 30.4, Sum: 152, Min: 21, Max: 46
Column 2 - Mean: 32.8, Sum: 164, Min: 17, Max: 44
Column 3 - Mean: 26.8, Sum: 134, Min: 15, Max: 39
Column 4 - Mean: 32.4, Sum: 162, Min: 21, Max: 44
Column 5 - Mean: 28.4, Sum: 142, Min: 12, Max: 40


- Task 3

In [12]:
identity_matrix = np.eye(4)


np.fill_diagonal(identity_matrix, identity_matrix.diagonal() + 5)


identity_matrix[-1, :] = 1


print("Modified matrix:\n", identity_matrix)


Modified matrix:
 [[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [1. 1. 1. 1.]]


- Task 4

In [13]:
arr_random = np.random.randint(0, 21, 15)


unique_values, counts = np.unique(arr_random, return_counts=True)
occurrences = dict(zip(unique_values, counts))


indices_greater_than_10 = np.where(arr_random > 10)[0]


print("Array:", arr_random)
print("Occurrences of each unique value:", occurrences)
print("Indices of elements greater than 10:", indices_greater_than_10)


Array: [ 9  1  7 16  7 18 17 14  0  3 15  3  6 20 16]
Occurrences of each unique value: {0: 1, 1: 1, 3: 2, 6: 1, 7: 2, 9: 1, 14: 1, 15: 1, 16: 2, 17: 1, 18: 1, 20: 1}
Indices of elements greater than 10: [ 3  5  6  7 10 13 14]


- Task 5

In [14]:
arr_float = np.random.rand(3, 4)


arr_rounded = np.round(arr_float, 2)


arr_rounded[:, 1] = 0.5


print("Modified array:\n", arr_rounded)


Modified array:
 [[0.1  0.5  0.97 0.11]
 [0.62 0.5  0.59 0.55]
 [0.43 0.5  0.7  0.17]]
